const express=require('express')
const { generate, verifyOtp,loggedIn,logout, login, forgetPasswordOtp, verifyForgetOtp, resetPassword, resentOtp, fetchUser, editUser } = require('../controller/userController')
const { getProducts, findProduct } = require('../controller/ProductContoller')
const { AddtoCart, getCartData, IncrementProduct, deleteCart } = require('../controller/CartController')
const { AddToList, getWishList, deleteWishlist } = require('../controller/WishListController')

const router=express.Router()

router.post('/generateOtp',generate)
router.post("/resendOtp",resentOtp)
router.post('/verifyOtp',verifyOtp)
router.get('/checkLogStatus',loggedIn)
router.get('/logout',logout)
router.post('/login',login)
router.get("/getProducts",getProducts)
router.post("/addToCart",AddtoCart)
router.get("/getCartData",getCartData)
router.delete("/deleteCart",deleteCart)
router.post("/incrementProduct",IncrementProduct)
router.post("/findProduct/:id",findProduct)
router.post("/wishlist",AddToList)
router.get("/getWishlist",getWishList)
router.post("/deleteWish",deleteWishlist)
router.get("/userData",fetchUser)
router.patch("/editUser",editUser)
router.post("/forgetPasswordOtp",forgetPasswordOtp)
router.post("/verifyForgetOtp",verifyForgetOtp)
router.patch("/resetPassword",resetPassword)
module.exports=router