version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: swiftcart_frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend:
    build: ./backend
    container_name: swiftcart_backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
